### ISSUE TITLE
Shodan API commited to repo

### ISSUE THREAD

**Issue by mattkduran** [crinny/goip#2]
Hi there,
It looks like you accidentally committed your Shodan API key to your repo (line 5 in config.py). You should follow the steps that Github outlines here on removing it from your repo history:

https://help.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

Thanks!
Matt

**Comment by crinny** [comment]
Hi! Thank you for pointing out, though if you search this key on GitHub, you can see it was published before me.
